version: '3'
services:
  rstudio:
    build: .
    image: takyam15/my-rstudio:latest
    container_name: rstudio
    env_file:
        - ./.env
    ports:
      - 8787:8787
    volumes:
      - ./R:/home/rstudio
    tty: true
    stdin_open: true